# Generated by Django 5.0.2 on 2024-02-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerId', models.IntegerField()),
                ('playerBirthYear', models.IntegerField()),
                ('playerBirthMonth', models.IntegerField()),
                ('playerBirthDay', models.IntegerField()),
                ('birthCountry', models.CharField(max_length=100)),
                ('birthState', models.CharField(max_length=100)),
                ('birthCity', models.CharField(max_length=100)),
                ('playerDeathYear', models.IntegerField()),
                ('playerDeathMonth', models.IntegerField()),
                ('playerDeathDay', models.IntegerField()),
                ('deathCountry', models.CharField(max_length=100)),
                ('deathState', models.CharField(max_length=100)),
                ('deathCity', models.CharField(max_length=100)),
                ('nameFirst', models.CharField(max_length=50)),
                ('nameLast', models.CharField(max_length=50)),
                ('nameGiven', models.CharField(max_length=100)),
                ('weight', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('bats', models.CharField(max_length=1)),
                ('throws', models.CharField(max_length=1)),
                ('debut', models.CharField(max_length=100)),
                ('finalGame', models.CharField(max_length=100)),
                ('retroID', models.CharField(max_length=100)),
                ('bbrefID', models.CharField(max_length=100)),
            ],
        ),
    ]
